export const COUNTRIES = [
  { id: "" },
  { id: "AL" },
  { id: "AT" },
  { id: "BE" },
  { id: "BG" },
  { id: "HR" },
  { id: "CH" },
  { id: "CZ" },
  { id: "DE" },
  { id: "DK" },
  { id: "ES" },
  { id: "FI" },
  { id: "FR" },
  { id: "GB" },
  { id: "GR" },
  { id: "HU" },
  { id: "IT" },
  { id: "LU" },
  { id: "NL" },
  { id: "NO" },
  { id: "PT" },
  { id: "RO" },
  { id: "SE" },
  { id: "SK" },
  { id: "TR" },
  { id: "UA" },
];
